---
name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Only deploy if CI workflow completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare deployment folder
        run: |
          mkdir -p deploy
          cp index.html deploy/
          cp -r css deploy/
          cp -r js deploy/
          cp -r data deploy/
          find deploy -name "PerformanceBenchmark.js" -delete
          find deploy -name "PerformanceDashboard.js" -delete

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: deploy
          clean-exclude: pr-preview/
          force: false
