---
name: github pages

"on":
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    env:
      PR_PATH: pr-${{ github.event.pull_request.number }}
      DOMAIN: ${{ github.repository_owner }}.github.io
      REPO_NAME: ${{ github.event.repository.name }}
      PREVIEW_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-${{ github.event.pull_request.number }}/
    steps:
      - name: Comment on PR start
        if: github.event_name == 'pull_request_target' && github.event.pull_request.number
        uses: hasura/comment-progress@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.pull_request.number }}
          id: deploy-preview
          message: "Starting deployment of preview ⏳..."

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          submodules: false

      - name: Prepare static files
        run: |
          rm -rf public
          mkdir public
          rsync -av \
            --exclude=public \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='.DS_Store' ./ public/
          # Verify that we have an index.html file
          if [ ! -f "public/index.html" ]; then
            echo "Error: index.html not found in public directory"
            exit 1
          fi
          echo "Files prepared for deployment:"
          ls -la public/

      - name: Debug environment
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "PR path: ${{ env.PR_PATH }}"
          echo "Preview URL: ${{ env.PREVIEW_URL }}"
          echo "Repository: ${{ github.repository }}"

      - name: Deploy to production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Deploy preview
        if: github.event_name == 'pull_request_target' && github.event.pull_request.number
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ${{ env.PR_PATH }}
          keep_files: true

      - name: Wait for GitHub Pages deployment
        if: github.event_name == 'pull_request_target' && github.event.pull_request.number
        run: |
          echo "Waiting for GitHub Pages to deploy..."
          echo "Preview should be available at: ${{ env.PREVIEW_URL }}"
          sleep 30

      - name: Update PR comment
        if: github.event_name == 'pull_request_target' && github.event.pull_request.number
        uses: hasura/comment-progress@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.pull_request.number }}
          id: deploy-preview
          message: |
            ✅ Preview ready:
            ${{ env.PREVIEW_URL }}

            Changes may take a few minutes to propagate.

      - name: Comment on failure
        if: failure() && github.event_name == 'pull_request_target' && github.event.pull_request.number
        uses: hasura/comment-progress@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.pull_request.number }}
          id: deploy-preview
          message: |
            ❌ Preview deployment failed. Please check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.
