---
name: delete preview on PR close

'on':
  pull_request_target:
    types: [closed]

jobs:
  delete_preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    env:
      PR_PATH: pr-${{ github.event.pull_request.number }}
      PREVIEW_REPO_URL: https://github.com/${{ github.repository }}/tree/gh-pages/pr-${{ github.event.pull_request.number }}/  # yamllint disable-line rule:line-length
    steps:
      - name: make empty dir
        run: mkdir public

      - name: delete folder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ${{ env.PR_PATH }}

      - name: Comment on PR
        uses: hasura/comment-progress@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.pull_request.number }}
          id: deploy-preview
          message: |
            🪓 PR closed, deleted preview:
            ${{ env.PREVIEW_REPO_URL }}
